# Generated by Django 2.0.1 on 2018-11-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liuyan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='联系地址'),
        ),
    ]
